### ISSUE TITLE
Calculated Column - Not removing quotes from the DAX Expression

### ISSUE THREAD

**Issue by thedaxshepherd** [m-kovalsky/ModelAutoBuild#1]
If a calculated column is such that the DAX code generates a quoted string it will not be removed by the ModelAutoBuild.cs file.
The ModelAutoBuildExample.xlsx works because the one calculated column is a simple SUM without anything that would generate a quoted string. But as soon as I create a Calculated Column such as a PATH(id, parent_Id) or a CALCULATE as soon as the comma is added it generates a quoted string.

 The current code only removes the quotes from the measures. 

One workaround I am using is to remove the quotes in the same else block that creates the Calculated Column. Or else I would need to do it similar to the Measure code and iterate through each Calculated Column. 
Note: I know the best method is to not create calculated columns and push that down to the database layer

**Comment by m-kovalsky** [comment]
Thanks for reporting. This is now fixed in v1.3.1.

https://github.com/m-kovalsky/ModelAutoBuild/releases/
