### ISSUE TITLE
FormatDAX Deprecated in Tabular Editor Version 2.13.0

### ISSUE THREAD

**Issue by thedaxshepherd** [m-kovalsky/ModelAutoBuild#2]
With the new version of Tabular Editor 2.13.0 the FormatDax method has been deprecated. 
https://docs.tabulareditor.com/FormatDax.html 
This is in an effort to reduce the workload on the Dax Formatter site.
The proposed solution is to use alternative syntax such as FormatDax(Model.AllMeasures); so that it is done in a single request.

When enabling DAX Formatting in the Model Auto Build with the new Tabular Editor it does generate this message:

Script warning: This script is making multiple calls to the "FormatDax" method, which has been deprecated! Calls will be throttled to not overload the DaxFormatter.com service. To avoid throttling, please change your script to use the FormatDax extension method going forward. For more information, see: https://docs.tabulareditor.com/FormatDax.html

**Comment by m-kovalsky** [comment]
Thanks for bringing this up. This has been fixed in v1.3.2.

**Comment by thedaxshepherd** [comment]
v1.3.2 works without error for Measures. When enabling it for Calculated Columns I get the below errors:
Script compilation errors:
Error CS1928 on line 288, col 6: 'TabularEditor.TOMWrapper.Column' does not contain a definition for 'FormatDax' and the best extension method overload 'TabularEditor.Scripting.ScriptHelper.FormatDax(TabularEditor.TOMWrapper.IDaxDependantObject)' has some invalid arguments
Error CS1929 on line 288, col 6: Instance argument: cannot convert from 'TabularEditor.TOMWrapper.Column' to 'TabularEditor.TOMWrapper.IDaxDependantObject'

**Comment by m-kovalsky** [comment]
Sorry about that. Please download 1.3.2 again as it has the fix for Calculated Columns. Thanks!
