### ISSUE TITLE
Model Permission

### ISSUE THREAD

**Issue by thedaxshepherd** [m-kovalsky/ModelAutoBuild#4]
The C# script does not support the Model Permission of Refresh and ReadRefresh. Unless this is to enforce best practices it would be helpful to have these permissions. 

As a workaround, I have added it manually to the script file.

**Comment by m-kovalsky** [comment]
Thanks. Hadn't included them since they're less commonly used. Fixed in v1.4.1.

https://github.com/m-kovalsky/ModelAutoBuild/releases/tag/1.4.1
