### ISSUE TITLE
Can v1.4 be run from command line

### ISSUE THREAD

**Issue by thedaxshepherd** [m-kovalsky/ModelAutoBuild#5]
I have not made the jump to v1.4. Waiting for time to test.

Can you still run the process from the command line without pasting the script in Tabular Editor?

I currently use a Powershell script to automate the build and deploy process.

**Comment by m-kovalsky** [comment]
Yes, you can still run it through the command line using the normal syntax. Just need to reference a blank .bim file (open Tabular Editor -> new model -> save this file). Here's the syntax for deploying to SSAS.

start /wait /d "C:\Program Files (x86)\Tabular Editor" TabularEditor.exe "C:\Desktop\BlankModelTemplate.bim" -D "ServerName" "DatabaseName" -S "C:\Desktop\ModelAutoBuild.cs"
