### ISSUE TITLE
Auto-Generate Relationship fails if similar named dimension table

### ISSUE THREAD

**Issue by thedaxshepherd** [m-kovalsky/ModelAutoBuild#6]
There currently was an existing Dimension named ServiceRouteMaster related to ServiceRouteMasterId in the current model.

For testing purposes I created a test column in the Fact Table named TestServiceRouteMasterId and another dimension table with the name of TestServiceRouteMaster. When I went to build this I got error messages about ambiguous paths. After creating some debug outputs I was able to determine that for the new dimension table it was getting the correct column from the fact table TransactionLines.TestServiceRouteMasterId but for the dimension it was using ServiceRouteMaster.ServiceRouteMasterId.

I determined this was due to it matching the same EndsWith pattern since it read the original ServiceRouteMaster column first. 

var dim = Model.Tables.FirstOrDefault(t => factColumn.Name.EndsWith(t.Name + keySuffix));

If I switch it to use Equals(t.Name + keySuffix)); it builds the correct relationship.

Could see this happening if someone had Location and CustLocation or StoreLocation.

**Comment by m-kovalsky** [comment]
Thanks for raising the issue. Fixed in [1.4.2](https://github.com/m-kovalsky/ModelAutoBuild/releases/tag/1.4.2).
