### ISSUE TITLE
Missing Decimal FormatString for Measures

### ISSUE THREAD

**Issue by thedaxshepherd** [m-kovalsky/ModelAutoBuild#8]
It is present for columns but not for measures.

BTW The way the code is written makes this project so extensible. If it fits my client's needs I could add more types like Decimal_OnePlace and Decimal_TwoPlace depending on how many decimal places they wanted to see by default.

**Comment by m-kovalsky** [comment]
Thanks for the feedback. I added more flexibility here for both columns & measures.
See the release notes in version [1.4.3](https://github.com/m-kovalsky/ModelAutoBuild/releases/tag/1.4.3).
